pub const PROP_EXP: u32 = 1001;
pub const PROP_BREAK_LEVEL: u32 = 1002;
pub const PROP_SATIATION_VAL: u32 = 1003;
pub const PROP_SATIATION_PENALTY_TIME: u32 = 1004;
pub const PROP_GEAR_START_VAL: u32 = 2001;
pub const PROP_GEAR_STOP_VAL: u32 = 2002;
pub const PROP_LEVEL: u32 = 4001;
pub const PROP_LAST_CHANGE_AVATAR_TIME: u32 = 10001;
pub const PROP_MAX_SPRING_VOLUME: u32 = 10002;
pub const PROP_CUR_SPRING_VOLUME: u32 = 10003;
pub const PROP_IS_SPRING_AUTO_USE: u32 = 10004;
pub const PROP_SPRING_AUTO_USE_PERCENT: u32 = 10005;
pub const PROP_IS_FLYABLE: u32 = 10006;
pub const PROP_IS_WEATHER_LOCKED: u32 = 10007;
pub const PROP_IS_GAME_TIME_LOCKED: u32 = 10008;
pub const PROP_IS_TRANSFERABLE: u32 = 10009;
pub const PROP_MAX_STAMINA: u32 = 10010;
pub const PROP_CUR_PERSIST_STAMINA: u32 = 10011;
pub const PROP_CUR_TEMPORARY_STAMINA: u32 = 10012;
pub const PROP_PLAYER_LEVEL: u32 = 10013;
pub const PROP_PLAYER_EXP: u32 = 10014;
pub const PROP_PLAYER_HCOIN: u32 = 10015;
pub const PROP_PLAYER_SCOIN: u32 = 10016;
pub const PROP_PLAYER_MP_SETTING_TYPE: u32 = 10017;
pub const PROP_IS_MP_MODE_AVAILABLE: u32 = 10018;
pub const PROP_PLAYER_WORLD_LEVEL: u32 = 10019;
pub const PROP_PLAYER_RESIN: u32 = 10020;
pub const PROP_PLAYER_WAIT_SUB_HCOIN: u32 = 10022;
pub const PROP_PLAYER_WAIT_SUB_SCOIN: u32 = 10023;
pub const PROP_IS_ONLY_MP_WITH_PS_PLAYER: u32 = 10024;
pub const PROP_PLAYER_MCOIN: u32 = 10025;
pub const PROP_PLAYER_WAIT_SUB_MCOIN: u32 = 10026;
pub const PROP_PLAYER_LEGENDARY_KEY: u32 = 10027;
pub const PROP_IS_HAS_FIRST_SHARE: u32 = 10028;
pub const PROP_PLAYER_FORGE_POINT: u32 = 10029;
pub const PROP_CUR_CLIMATE_METER: u32 = 10035;
pub const PROP_CUR_CLIMATE_TYPE: u32 = 10036;
pub const PROP_CUR_CLIMATE_AREA_ID: u32 = 10037;
pub const PROP_CUR_CLIMATE_AREA_CLIMATE_TYPE: u32 = 10038;
pub const PROP_PLAYER_WORLD_LEVEL_LIMIT: u32 = 10039;
pub const PROP_PLAYER_WORLD_LEVEL_ADJUST_CD: u32 = 10040;
pub const PROP_PLAYER_LEGENDARY_DAILY_TASK_NUM: u32 = 10041;
pub const PROP_PLAYER_HOME_COIN: u32 = 10042;
pub const PROP_PLAYER_WAIT_SUB_HOME_COIN: u32 = 10043;
pub const PROP_IS_AUTO_UNLOCK_SPECIFIC_EQUIP: u32 = 10044;
pub const PROP_PLAYER_GCG_COIN: u32 = 10045;
pub const PROP_PLAYER_WAIT_SUB_GCG_COIN: u32 = 10046;
pub const PROP_PLAYER_ONLINE_TIME: u32 = 10047;
pub const PROP_IS_DIVEABLE: u32 = 10048;
pub const PROP_MAX_DIVE_STAMINA: u32 = 10049;
pub const PROP_CUR_PERSIST_DIVE_STAMINA: u32 = 10050;
pub const PROP_IS_CAN_PUT_FIVE_STAR_RELIQUARY: u32 = 10051;
pub const PROP_IS_AUTO_LOCK_FIVE_STAR_RELIQUARY: u32 = 10052;
pub const PROP_PLAYER_ROLE_COMBAT_COIN: u32 = 10053;
pub const PROP_CUR_PHLOGISTON: u32 = 10054;
pub const PROP_RELIQUARY_TEMPORARY_EXP: u32 = 10055;
pub const PROP_IS_MP_CROSS_PLATFORM_ENABLED: u32 = 10056;
pub const PROP_IS_ONLY_MP_WITH_PLATFORM_PLAYER: u32 = 10057;

#[repr(u32)]
#[allow(non_camel_case_types)]
#[derive(Debug, Default, PartialEq, Eq, Hash, Clone, Copy, serde::Deserialize)]
pub enum FightPropType {
    #[default]
    FIGHT_PROP_NONE = 0,
    FIGHT_PROP_BASE_HP = 1,
    FIGHT_PROP_HP = 2,
    FIGHT_PROP_HP_PERCENT = 3,
    FIGHT_PROP_BASE_ATTACK = 4,
    FIGHT_PROP_ATTACK = 5,
    FIGHT_PROP_ATTACK_PERCENT = 6,
    FIGHT_PROP_BASE_DEFENSE = 7,
    FIGHT_PROP_DEFENSE = 8,
    FIGHT_PROP_DEFENSE_PERCENT = 9,
    FIGHT_PROP_BASE_SPEED = 10,
    FIGHT_PROP_SPEED_PERCENT = 11,
    FIGHT_PROP_HP_MP_PERCENT = 12,
    FIGHT_PROP_ATTACK_MP_PERCENT = 13,
    FIGHT_PROP_CRITICAL = 20,
    FIGHT_PROP_ANTI_CRITICAL = 21,
    FIGHT_PROP_CRITICAL_HURT = 22,
    FIGHT_PROP_CHARGE_EFFICIENCY = 23,
    FIGHT_PROP_ADD_HURT = 24,
    FIGHT_PROP_SUB_HURT = 25,
    FIGHT_PROP_HEAL_ADD = 26,
    FIGHT_PROP_HEALED_ADD = 27,
    FIGHT_PROP_ELEMENT_MASTERY = 28,
    FIGHT_PROP_PHYSICAL_SUB_HURT = 29,
    FIGHT_PROP_PHYSICAL_ADD_HURT = 30,
    FIGHT_PROP_DEFENCE_IGNORE_RATIO = 31,
    FIGHT_PROP_DEFENCE_IGNORE_DELTA = 32,
    FIGHT_PROP_FIRE_ADD_HURT = 40,
    FIGHT_PROP_ELEC_ADD_HURT = 41,
    FIGHT_PROP_WATER_ADD_HURT = 42,
    FIGHT_PROP_GRASS_ADD_HURT = 43,
    FIGHT_PROP_WIND_ADD_HURT = 44,
    FIGHT_PROP_ROCK_ADD_HURT = 45,
    FIGHT_PROP_ICE_ADD_HURT = 46,
    FIGHT_PROP_HIT_HEAD_ADD_HURT = 47,
    FIGHT_PROP_FIRE_SUB_HURT = 50,
    FIGHT_PROP_ELEC_SUB_HURT = 51,
    FIGHT_PROP_WATER_SUB_HURT = 52,
    FIGHT_PROP_GRASS_SUB_HURT = 53,
    FIGHT_PROP_WIND_SUB_HURT = 54,
    FIGHT_PROP_ROCK_SUB_HURT = 55,
    FIGHT_PROP_ICE_SUB_HURT = 56,
    FIGHT_PROP_EFFECT_HIT = 60,
    FIGHT_PROP_EFFECT_RESIST = 61,
    FIGHT_PROP_FREEZE_RESIST = 62,
    FIGHT_PROP_TORPOR_RESIST = 63,
    FIGHT_PROP_DIZZY_RESIST = 64,
    FIGHT_PROP_FREEZE_SHORTEN = 65,
    FIGHT_PROP_TORPOR_SHORTEN = 66,
    FIGHT_PROP_DIZZY_SHORTEN = 67,
    FIGHT_PROP_MAX_FIRE_ENERGY = 70,
    FIGHT_PROP_MAX_ELEC_ENERGY = 71,
    FIGHT_PROP_MAX_WATER_ENERGY = 72,
    FIGHT_PROP_MAX_GRASS_ENERGY = 73,
    FIGHT_PROP_MAX_WIND_ENERGY = 74,
    FIGHT_PROP_MAX_ICE_ENERGY = 75,
    FIGHT_PROP_MAX_ROCK_ENERGY = 76,
    FIGHT_PROP_MAX_SPECIAL_ENERGY = 77,
    FIGHT_PROP_START_SPECIAL_ENERGY = 78,
    FIGHT_PROP_SKILL_CD_MINUS_RATIO = 80,
    FIGHT_PROP_SHIELD_COST_MINUS_RATIO = 81,
    FIGHT_PROP_CUR_FIRE_ENERGY = 1000,
    FIGHT_PROP_CUR_ELEC_ENERGY = 1001,
    FIGHT_PROP_CUR_WATER_ENERGY = 1002,
    FIGHT_PROP_CUR_GRASS_ENERGY = 1003,
    FIGHT_PROP_CUR_WIND_ENERGY = 1004,
    FIGHT_PROP_CUR_ICE_ENERGY = 1005,
    FIGHT_PROP_CUR_ROCK_ENERGY = 1006,
    FIGHT_PROP_CUR_SPECIAL_ENERGY = 1007,
    FIGHT_PROP_CUR_HP = 1010,
    FIGHT_PROP_MAX_HP = 2000,
    FIGHT_PROP_CUR_ATTACK = 2001,
    FIGHT_PROP_CUR_DEFENSE = 2002,
    FIGHT_PROP_CUR_SPEED = 2003,
    FIGHT_PROP_CUR_HP_DEBTS = 2004,
    FIGHT_PROP_CUR_HP_PAID_DEBTS = 2005,
    FIGHT_PROP_CUR_NATLAN_HP = 2006,
    FIGHT_PROP_NONEXTRA_ATTACK = 3000,
    FIGHT_PROP_NONEXTRA_DEFENSE = 3001,
    FIGHT_PROP_NONEXTRA_CRITICAL = 3002,
    FIGHT_PROP_NONEXTRA_ANTI_CRITICAL = 3003,
    FIGHT_PROP_NONEXTRA_CRITICAL_HURT = 3004,
    FIGHT_PROP_NONEXTRA_CHARGE_EFFICIENCY = 3005,
    FIGHT_PROP_NONEXTRA_ELEMENT_MASTERY = 3006,
    FIGHT_PROP_NONEXTRA_PHYSICAL_SUB_HURT = 3007,
    FIGHT_PROP_NONEXTRA_FIRE_ADD_HURT = 3008,
    FIGHT_PROP_NONEXTRA_ELEC_ADD_HURT = 3009,
    FIGHT_PROP_NONEXTRA_WATER_ADD_HURT = 3010,
    FIGHT_PROP_NONEXTRA_GRASS_ADD_HURT = 3011,
    FIGHT_PROP_NONEXTRA_WIND_ADD_HURT = 3012,
    FIGHT_PROP_NONEXTRA_ROCK_ADD_HURT = 3013,
    FIGHT_PROP_NONEXTRA_ICE_ADD_HURT = 3014,
    FIGHT_PROP_NONEXTRA_FIRE_SUB_HURT = 3015,
    FIGHT_PROP_NONEXTRA_ELEC_SUB_HURT = 3016,
    FIGHT_PROP_NONEXTRA_WATER_SUB_HURT = 3017,
    FIGHT_PROP_NONEXTRA_GRASS_SUB_HURT = 3018,
    FIGHT_PROP_NONEXTRA_WIND_SUB_HURT = 3019,
    FIGHT_PROP_NONEXTRA_ROCK_SUB_HURT = 3020,
    FIGHT_PROP_NONEXTRA_ICE_SUB_HURT = 3021,
    FIGHT_PROP_NONEXTRA_SKILL_CD_MINUS_RATIO = 3022,
    FIGHT_PROP_NONEXTRA_SHIELD_COST_MINUS_RATIO = 3023,
    FIGHT_PROP_NONEXTRA_PHYSICAL_ADD_HURT = 3024,
    FIGHT_PROP_ELEM_REACT_CRITICAL = 3025,
    FIGHT_PROP_ELEM_REACT_CRITICAL_HURT = 3026,
    FIGHT_PROP_ELEM_REACT_EXPLODE_CRITICAL = 3027,
    FIGHT_PROP_ELEM_REACT_EXPLODE_CRITICAL_HURT = 3028,
    FIGHT_PROP_ELEM_REACT_SWIRL_CRITICAL = 3029,
    FIGHT_PROP_ELEM_REACT_SWIRL_CRITICAL_HURT = 3030,
    FIGHT_PROP_ELEM_REACT_ELECTRIC_CRITICAL = 3031,
    FIGHT_PROP_ELEM_REACT_ELECTRIC_CRITICAL_HURT = 3032,
    FIGHT_PROP_ELEM_REACT_SCONDUCT_CRITICAL = 3033,
    FIGHT_PROP_ELEM_REACT_SCONDUCT_CRITICAL_HURT = 3034,
    FIGHT_PROP_ELEM_REACT_BURN_CRITICAL = 3035,
    FIGHT_PROP_ELEM_REACT_BURN_CRITICAL_HURT = 3036,
    FIGHT_PROP_ELEM_REACT_FROZENBROKEN_CRITICAL = 3037,
    FIGHT_PROP_ELEM_REACT_FROZENBROKEN_CRITICAL_HURT = 3038,
    FIGHT_PROP_ELEM_REACT_OVERGROW_CRITICAL = 3039,
    FIGHT_PROP_ELEM_REACT_OVERGROW_CRITICAL_HURT = 3040,
    FIGHT_PROP_ELEM_REACT_OVERGROW_FIRE_CRITICAL = 3041,
    FIGHT_PROP_ELEM_REACT_OVERGROW_FIRE_CRITICAL_HURT = 3042,
    FIGHT_PROP_ELEM_REACT_OVERGROW_ELECTRIC_CRITICAL = 3043,
    FIGHT_PROP_ELEM_REACT_OVERGROW_ELECTRIC_CRITICAL_HURT = 3044,
    FIGHT_PROP_BASE_ELEM_REACT_CRITICAL = 3045,
    FIGHT_PROP_BASE_ELEM_REACT_CRITICAL_HURT = 3046,
}

impl FightPropType {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "FIGHT_PROP_NONE" => Some(FightPropType::FIGHT_PROP_NONE),
            "FIGHT_PROP_BASE_HP" => Some(FightPropType::FIGHT_PROP_BASE_HP),
            "FIGHT_PROP_HP" => Some(FightPropType::FIGHT_PROP_HP),
            "FIGHT_PROP_HP_PERCENT" => Some(FightPropType::FIGHT_PROP_HP_PERCENT),
            "FIGHT_PROP_BASE_ATTACK" => Some(FightPropType::FIGHT_PROP_BASE_ATTACK),
            "FIGHT_PROP_ATTACK" => Some(FightPropType::FIGHT_PROP_ATTACK),
            "FIGHT_PROP_ATTACK_PERCENT" => Some(FightPropType::FIGHT_PROP_ATTACK_PERCENT),
            "FIGHT_PROP_BASE_DEFENSE" => Some(FightPropType::FIGHT_PROP_BASE_DEFENSE),
            "FIGHT_PROP_DEFENSE" => Some(FightPropType::FIGHT_PROP_DEFENSE),
            "FIGHT_PROP_DEFENSE_PERCENT" => Some(FightPropType::FIGHT_PROP_DEFENSE_PERCENT),
            "FIGHT_PROP_BASE_SPEED" => Some(FightPropType::FIGHT_PROP_BASE_SPEED),
            "FIGHT_PROP_SPEED_PERCENT" => Some(FightPropType::FIGHT_PROP_SPEED_PERCENT),
            "FIGHT_PROP_HP_MP_PERCENT" => Some(FightPropType::FIGHT_PROP_HP_MP_PERCENT),
            "FIGHT_PROP_ATTACK_MP_PERCENT" => Some(FightPropType::FIGHT_PROP_ATTACK_MP_PERCENT),
            "FIGHT_PROP_CRITICAL" => Some(FightPropType::FIGHT_PROP_CRITICAL),
            "FIGHT_PROP_ANTI_CRITICAL" => Some(FightPropType::FIGHT_PROP_ANTI_CRITICAL),
            "FIGHT_PROP_CRITICAL_HURT" => Some(FightPropType::FIGHT_PROP_CRITICAL_HURT),
            "FIGHT_PROP_CHARGE_EFFICIENCY" => Some(FightPropType::FIGHT_PROP_CHARGE_EFFICIENCY),
            "FIGHT_PROP_ADD_HURT" => Some(FightPropType::FIGHT_PROP_ADD_HURT),
            "FIGHT_PROP_SUB_HURT" => Some(FightPropType::FIGHT_PROP_SUB_HURT),
            "FIGHT_PROP_HEAL_ADD" => Some(FightPropType::FIGHT_PROP_HEAL_ADD),
            "FIGHT_PROP_HEALED_ADD" => Some(FightPropType::FIGHT_PROP_HEALED_ADD),
            "FIGHT_PROP_ELEMENT_MASTERY" => Some(FightPropType::FIGHT_PROP_ELEMENT_MASTERY),
            "FIGHT_PROP_PHYSICAL_SUB_HURT" => Some(FightPropType::FIGHT_PROP_PHYSICAL_SUB_HURT),
            "FIGHT_PROP_PHYSICAL_ADD_HURT" => Some(FightPropType::FIGHT_PROP_PHYSICAL_ADD_HURT),
            "FIGHT_PROP_DEFENCE_IGNORE_RATIO" => {
                Some(FightPropType::FIGHT_PROP_DEFENCE_IGNORE_RATIO)
            }
            "FIGHT_PROP_DEFENCE_IGNORE_DELTA" => {
                Some(FightPropType::FIGHT_PROP_DEFENCE_IGNORE_DELTA)
            }
            "FIGHT_PROP_FIRE_ADD_HURT" => Some(FightPropType::FIGHT_PROP_FIRE_ADD_HURT),
            "FIGHT_PROP_ELEC_ADD_HURT" => Some(FightPropType::FIGHT_PROP_ELEC_ADD_HURT),
            "FIGHT_PROP_WATER_ADD_HURT" => Some(FightPropType::FIGHT_PROP_WATER_ADD_HURT),
            "FIGHT_PROP_GRASS_ADD_HURT" => Some(FightPropType::FIGHT_PROP_GRASS_ADD_HURT),
            "FIGHT_PROP_WIND_ADD_HURT" => Some(FightPropType::FIGHT_PROP_WIND_ADD_HURT),
            "FIGHT_PROP_ROCK_ADD_HURT" => Some(FightPropType::FIGHT_PROP_ROCK_ADD_HURT),
            "FIGHT_PROP_ICE_ADD_HURT" => Some(FightPropType::FIGHT_PROP_ICE_ADD_HURT),
            "FIGHT_PROP_HIT_HEAD_ADD_HURT" => Some(FightPropType::FIGHT_PROP_HIT_HEAD_ADD_HURT),
            "FIGHT_PROP_FIRE_SUB_HURT" => Some(FightPropType::FIGHT_PROP_FIRE_SUB_HURT),
            "FIGHT_PROP_ELEC_SUB_HURT" => Some(FightPropType::FIGHT_PROP_ELEC_SUB_HURT),
            "FIGHT_PROP_WATER_SUB_HURT" => Some(FightPropType::FIGHT_PROP_WATER_SUB_HURT),
            "FIGHT_PROP_GRASS_SUB_HURT" => Some(FightPropType::FIGHT_PROP_GRASS_SUB_HURT),
            "FIGHT_PROP_WIND_SUB_HURT" => Some(FightPropType::FIGHT_PROP_WIND_SUB_HURT),
            "FIGHT_PROP_ROCK_SUB_HURT" => Some(FightPropType::FIGHT_PROP_ROCK_SUB_HURT),
            "FIGHT_PROP_ICE_SUB_HURT" => Some(FightPropType::FIGHT_PROP_ICE_SUB_HURT),
            "FIGHT_PROP_EFFECT_HIT" => Some(FightPropType::FIGHT_PROP_EFFECT_HIT),
            "FIGHT_PROP_EFFECT_RESIST" => Some(FightPropType::FIGHT_PROP_EFFECT_RESIST),
            "FIGHT_PROP_FREEZE_RESIST" => Some(FightPropType::FIGHT_PROP_FREEZE_RESIST),
            "FIGHT_PROP_TORPOR_RESIST" => Some(FightPropType::FIGHT_PROP_TORPOR_RESIST),
            "FIGHT_PROP_DIZZY_RESIST" => Some(FightPropType::FIGHT_PROP_DIZZY_RESIST),
            "FIGHT_PROP_FREEZE_SHORTEN" => Some(FightPropType::FIGHT_PROP_FREEZE_SHORTEN),
            "FIGHT_PROP_TORPOR_SHORTEN" => Some(FightPropType::FIGHT_PROP_TORPOR_SHORTEN),
            "FIGHT_PROP_DIZZY_SHORTEN" => Some(FightPropType::FIGHT_PROP_DIZZY_SHORTEN),
            "FIGHT_PROP_MAX_FIRE_ENERGY" => Some(FightPropType::FIGHT_PROP_MAX_FIRE_ENERGY),
            "FIGHT_PROP_MAX_ELEC_ENERGY" => Some(FightPropType::FIGHT_PROP_MAX_ELEC_ENERGY),
            "FIGHT_PROP_MAX_WATER_ENERGY" => Some(FightPropType::FIGHT_PROP_MAX_WATER_ENERGY),
            "FIGHT_PROP_MAX_GRASS_ENERGY" => Some(FightPropType::FIGHT_PROP_MAX_GRASS_ENERGY),
            "FIGHT_PROP_MAX_WIND_ENERGY" => Some(FightPropType::FIGHT_PROP_MAX_WIND_ENERGY),
            "FIGHT_PROP_MAX_ICE_ENERGY" => Some(FightPropType::FIGHT_PROP_MAX_ICE_ENERGY),
            "FIGHT_PROP_MAX_ROCK_ENERGY" => Some(FightPropType::FIGHT_PROP_MAX_ROCK_ENERGY),
            "FIGHT_PROP_MAX_SPECIAL_ENERGY" => Some(FightPropType::FIGHT_PROP_MAX_SPECIAL_ENERGY),
            "FIGHT_PROP_START_SPECIAL_ENERGY" => {
                Some(FightPropType::FIGHT_PROP_START_SPECIAL_ENERGY)
            }
            "FIGHT_PROP_SKILL_CD_MINUS_RATIO" => {
                Some(FightPropType::FIGHT_PROP_SKILL_CD_MINUS_RATIO)
            }
            "FIGHT_PROP_SHIELD_COST_MINUS_RATIO" => {
                Some(FightPropType::FIGHT_PROP_SHIELD_COST_MINUS_RATIO)
            }
            "FIGHT_PROP_CUR_FIRE_ENERGY" => Some(FightPropType::FIGHT_PROP_CUR_FIRE_ENERGY),
            "FIGHT_PROP_CUR_ELEC_ENERGY" => Some(FightPropType::FIGHT_PROP_CUR_ELEC_ENERGY),
            "FIGHT_PROP_CUR_WATER_ENERGY" => Some(FightPropType::FIGHT_PROP_CUR_WATER_ENERGY),
            "FIGHT_PROP_CUR_GRASS_ENERGY" => Some(FightPropType::FIGHT_PROP_CUR_GRASS_ENERGY),
            "FIGHT_PROP_CUR_WIND_ENERGY" => Some(FightPropType::FIGHT_PROP_CUR_WIND_ENERGY),
            "FIGHT_PROP_CUR_ICE_ENERGY" => Some(FightPropType::FIGHT_PROP_CUR_ICE_ENERGY),
            "FIGHT_PROP_CUR_ROCK_ENERGY" => Some(FightPropType::FIGHT_PROP_CUR_ROCK_ENERGY),
            "FIGHT_PROP_CUR_SPECIAL_ENERGY" => Some(FightPropType::FIGHT_PROP_CUR_SPECIAL_ENERGY),
            "FIGHT_PROP_CUR_HP" => Some(FightPropType::FIGHT_PROP_CUR_HP),
            "FIGHT_PROP_MAX_HP" => Some(FightPropType::FIGHT_PROP_MAX_HP),
            "FIGHT_PROP_CUR_ATTACK" => Some(FightPropType::FIGHT_PROP_CUR_ATTACK),
            "FIGHT_PROP_CUR_DEFENSE" => Some(FightPropType::FIGHT_PROP_CUR_DEFENSE),
            "FIGHT_PROP_CUR_SPEED" => Some(FightPropType::FIGHT_PROP_CUR_SPEED),
            "FIGHT_PROP_CUR_HP_DEBTS" => Some(FightPropType::FIGHT_PROP_CUR_HP_DEBTS),
            "FIGHT_PROP_CUR_HP_PAID_DEBTS" => Some(FightPropType::FIGHT_PROP_CUR_HP_PAID_DEBTS),
            "FIGHT_PROP_CUR_NATLAN_HP" => Some(FightPropType::FIGHT_PROP_CUR_NATLAN_HP),
            "FIGHT_PROP_NONEXTRA_ATTACK" => Some(FightPropType::FIGHT_PROP_NONEXTRA_ATTACK),
            "FIGHT_PROP_NONEXTRA_DEFENSE" => Some(FightPropType::FIGHT_PROP_NONEXTRA_DEFENSE),
            "FIGHT_PROP_NONEXTRA_CRITICAL" => Some(FightPropType::FIGHT_PROP_NONEXTRA_CRITICAL),
            "FIGHT_PROP_NONEXTRA_ANTI_CRITICAL" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_ANTI_CRITICAL)
            }
            "FIGHT_PROP_NONEXTRA_CRITICAL_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_CRITICAL_HURT)
            }
            "FIGHT_PROP_NONEXTRA_CHARGE_EFFICIENCY" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_CHARGE_EFFICIENCY)
            }
            "FIGHT_PROP_NONEXTRA_ELEMENT_MASTERY" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_ELEMENT_MASTERY)
            }
            "FIGHT_PROP_NONEXTRA_PHYSICAL_SUB_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_PHYSICAL_SUB_HURT)
            }
            "FIGHT_PROP_NONEXTRA_FIRE_ADD_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_FIRE_ADD_HURT)
            }
            "FIGHT_PROP_NONEXTRA_ELEC_ADD_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_ELEC_ADD_HURT)
            }
            "FIGHT_PROP_NONEXTRA_WATER_ADD_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_WATER_ADD_HURT)
            }
            "FIGHT_PROP_NONEXTRA_GRASS_ADD_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_GRASS_ADD_HURT)
            }
            "FIGHT_PROP_NONEXTRA_WIND_ADD_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_WIND_ADD_HURT)
            }
            "FIGHT_PROP_NONEXTRA_ROCK_ADD_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_ROCK_ADD_HURT)
            }
            "FIGHT_PROP_NONEXTRA_ICE_ADD_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_ICE_ADD_HURT)
            }
            "FIGHT_PROP_NONEXTRA_FIRE_SUB_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_FIRE_SUB_HURT)
            }
            "FIGHT_PROP_NONEXTRA_ELEC_SUB_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_ELEC_SUB_HURT)
            }
            "FIGHT_PROP_NONEXTRA_WATER_SUB_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_WATER_SUB_HURT)
            }
            "FIGHT_PROP_NONEXTRA_GRASS_SUB_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_GRASS_SUB_HURT)
            }
            "FIGHT_PROP_NONEXTRA_WIND_SUB_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_WIND_SUB_HURT)
            }
            "FIGHT_PROP_NONEXTRA_ROCK_SUB_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_ROCK_SUB_HURT)
            }
            "FIGHT_PROP_NONEXTRA_ICE_SUB_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_ICE_SUB_HURT)
            }
            "FIGHT_PROP_NONEXTRA_SKILL_CD_MINUS_RATIO" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_SKILL_CD_MINUS_RATIO)
            }
            "FIGHT_PROP_NONEXTRA_SHIELD_COST_MINUS_RATIO" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_SHIELD_COST_MINUS_RATIO)
            }
            "FIGHT_PROP_NONEXTRA_PHYSICAL_ADD_HURT" => {
                Some(FightPropType::FIGHT_PROP_NONEXTRA_PHYSICAL_ADD_HURT)
            }
            "FIGHT_PROP_ELEM_REACT_CRITICAL" => Some(FightPropType::FIGHT_PROP_ELEM_REACT_CRITICAL),
            "FIGHT_PROP_ELEM_REACT_CRITICAL_HURT" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_CRITICAL_HURT)
            }
            "FIGHT_PROP_ELEM_REACT_EXPLODE_CRITICAL" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_EXPLODE_CRITICAL)
            }
            "FIGHT_PROP_ELEM_REACT_EXPLODE_CRITICAL_HURT" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_EXPLODE_CRITICAL_HURT)
            }
            "FIGHT_PROP_ELEM_REACT_SWIRL_CRITICAL" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_SWIRL_CRITICAL)
            }
            "FIGHT_PROP_ELEM_REACT_SWIRL_CRITICAL_HURT" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_SWIRL_CRITICAL_HURT)
            }
            "FIGHT_PROP_ELEM_REACT_ELECTRIC_CRITICAL" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_ELECTRIC_CRITICAL)
            }
            "FIGHT_PROP_ELEM_REACT_ELECTRIC_CRITICAL_HURT" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_ELECTRIC_CRITICAL_HURT)
            }
            "FIGHT_PROP_ELEM_REACT_SCONDUCT_CRITICAL" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_SCONDUCT_CRITICAL)
            }
            "FIGHT_PROP_ELEM_REACT_SCONDUCT_CRITICAL_HURT" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_SCONDUCT_CRITICAL_HURT)
            }
            "FIGHT_PROP_ELEM_REACT_BURN_CRITICAL" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_BURN_CRITICAL)
            }
            "FIGHT_PROP_ELEM_REACT_BURN_CRITICAL_HURT" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_BURN_CRITICAL_HURT)
            }
            "FIGHT_PROP_ELEM_REACT_FROZENBROKEN_CRITICAL" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_FROZENBROKEN_CRITICAL)
            }
            "FIGHT_PROP_ELEM_REACT_FROZENBROKEN_CRITICAL_HURT" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_FROZENBROKEN_CRITICAL_HURT)
            }
            "FIGHT_PROP_ELEM_REACT_OVERGROW_CRITICAL" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_OVERGROW_CRITICAL)
            }
            "FIGHT_PROP_ELEM_REACT_OVERGROW_CRITICAL_HURT" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_OVERGROW_CRITICAL_HURT)
            }
            "FIGHT_PROP_ELEM_REACT_OVERGROW_FIRE_CRITICAL" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_OVERGROW_FIRE_CRITICAL)
            }
            "FIGHT_PROP_ELEM_REACT_OVERGROW_FIRE_CRITICAL_HURT" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_OVERGROW_FIRE_CRITICAL_HURT)
            }
            "FIGHT_PROP_ELEM_REACT_OVERGROW_ELECTRIC_CRITICAL" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_OVERGROW_ELECTRIC_CRITICAL)
            }
            "FIGHT_PROP_ELEM_REACT_OVERGROW_ELECTRIC_CRITICAL_HURT" => {
                Some(FightPropType::FIGHT_PROP_ELEM_REACT_OVERGROW_ELECTRIC_CRITICAL_HURT)
            }
            "FIGHT_PROP_BASE_ELEM_REACT_CRITICAL" => {
                Some(FightPropType::FIGHT_PROP_BASE_ELEM_REACT_CRITICAL)
            }
            "FIGHT_PROP_BASE_ELEM_REACT_CRITICAL_HURT" => {
                Some(FightPropType::FIGHT_PROP_BASE_ELEM_REACT_CRITICAL_HURT)
            }
            // short name
            "hp" => Some(FightPropType::FIGHT_PROP_HP),
            "atk" => Some(FightPropType::FIGHT_PROP_ATTACK),
            "def" => Some(FightPropType::FIGHT_PROP_DEFENSE),
            "hp%" => Some(FightPropType::FIGHT_PROP_HP_PERCENT),
            "atk%" => Some(FightPropType::FIGHT_PROP_ATTACK_PERCENT),
            "def%" => Some(FightPropType::FIGHT_PROP_DEFENSE_PERCENT),
            "em" => Some(FightPropType::FIGHT_PROP_ELEMENT_MASTERY),
            "er" => Some(FightPropType::FIGHT_PROP_CHARGE_EFFICIENCY),
            "hb" => Some(FightPropType::FIGHT_PROP_HEAL_ADD),
            "heal" => Some(FightPropType::FIGHT_PROP_HEAL_ADD),
            "cd" => Some(FightPropType::FIGHT_PROP_CRITICAL_HURT),
            "cdmg" => Some(FightPropType::FIGHT_PROP_CRITICAL_HURT),
            "cr" => Some(FightPropType::FIGHT_PROP_CRITICAL),
            "crate" => Some(FightPropType::FIGHT_PROP_CRITICAL),
            "phys%" => Some(FightPropType::FIGHT_PROP_PHYSICAL_ADD_HURT),
            "dendro%" => Some(FightPropType::FIGHT_PROP_GRASS_ADD_HURT),
            "geo%" => Some(FightPropType::FIGHT_PROP_ROCK_ADD_HURT),
            "anemo%" => Some(FightPropType::FIGHT_PROP_WIND_ADD_HURT),
            "hydro%" => Some(FightPropType::FIGHT_PROP_WATER_ADD_HURT),
            "cryo%" => Some(FightPropType::FIGHT_PROP_ICE_ADD_HURT),
            "electro%" => Some(FightPropType::FIGHT_PROP_ELEC_ADD_HURT),
            "pyro%" => Some(FightPropType::FIGHT_PROP_FIRE_ADD_HURT),

            "maxhp" => Some(FightPropType::FIGHT_PROP_MAX_HP),
            "debt" => Some(FightPropType::FIGHT_PROP_CUR_HP_DEBTS),
            "paiddebt" => Some(FightPropType::FIGHT_PROP_CUR_HP_PAID_DEBTS),
            "specialenergy" => Some(FightPropType::FIGHT_PROP_CUR_SPECIAL_ENERGY),
            "startspecial" => Some(FightPropType::FIGHT_PROP_START_SPECIAL_ENERGY),
            "dmg" => Some(FightPropType::FIGHT_PROP_ADD_HURT),
            "cdr" => Some(FightPropType::FIGHT_PROP_SKILL_CD_MINUS_RATIO),
            "heali" => Some(FightPropType::FIGHT_PROP_HEALED_ADD),
            "shield" => Some(FightPropType::FIGHT_PROP_SHIELD_COST_MINUS_RATIO),
            "defi" => Some(FightPropType::FIGHT_PROP_DEFENCE_IGNORE_RATIO),

            "resall" => Some(FightPropType::FIGHT_PROP_SUB_HURT),
            "resanemo" => Some(FightPropType::FIGHT_PROP_WIND_SUB_HURT),
            "rescryo" => Some(FightPropType::FIGHT_PROP_ICE_SUB_HURT),
            "resdendro" => Some(FightPropType::FIGHT_PROP_GRASS_SUB_HURT),
            "reselectro" => Some(FightPropType::FIGHT_PROP_ELEC_SUB_HURT),
            "resgeo" => Some(FightPropType::FIGHT_PROP_ROCK_SUB_HURT),
            "reshydro" => Some(FightPropType::FIGHT_PROP_WATER_SUB_HURT),
            "respyro" => Some(FightPropType::FIGHT_PROP_FIRE_SUB_HURT),
            "resphys" => Some(FightPropType::FIGHT_PROP_PHYSICAL_SUB_HURT),

            _ => None,
        }
    }
}
